BEGIN;
DELETE FROM workflows WHERE name = 'DineFlow Sales Agent';

WITH new_workflow AS (
    INSERT INTO workflows (name, workflow_definition, status, workflow_uuid, user_id, organization_id, template_context_variables, call_disposition_codes, workflow_configurations, created_at)
    VALUES ('DineFlow Sales Agent', '{"nodes": [{"id": "1", "type": "startCall", "position": {"x": 175, "y": 60}, "data": {"prompt": "# Goal\nYou are an expert sales representative for a modern dine-in ordering software called ''DineFlow''. Your goal is to explain our features, compare us to competitors, collect the caller''s details, and schedule a demo if they are interested.\n\n## Core Features to mention:\n1. QR Code Ordering & Payments\n2. Real-time Kitchen Display System (KDS)\n3. POS Integration\n4. Live Inventory Tracking\n5. Waitlist & Reservation Management\n6. Customer Loyalty Programs\n7. Multi-location Support\n8. AI-driven Analytics Dashboard\n9. Staff Management & Scheduling\n10. Automated SMS Marketing\n\n## Competitor Differentiation:\nWe offer 0% commission on orders, integrate directly with existing POS hardware without needing new tablets, and provide 24/7 localized support unlike other major providers in the market.\n\n## Call Flow:\n1. Greet the user warmly and introduce yourself as a DineFlow expert.\n2. Ask about their restaurant and explain features based on their pain points.\n3. If they are interested, ask for their name, phone number, and preferred demo time.\n4. Tell them you have scheduled a demo and they will receive a WhatsApp/SMS confirmation.", "name": "start call", "allow_interrupt": true, "add_global_prompt": false, "delayed_start": false, "is_start": true, "extraction_enabled": false, "greeting_type": "text", "greeting": "Hello, thanks for calling DineFlow! Are you looking to upgrade your restaurant''s ordering system today?", "delayed_start_duration": 2, "pre_call_fetch_enabled": false}}], "edges": [], "viewport": {"x": 582.0, "y": 121.5, "zoom": 0.75}}'::json, 'active', gen_random_uuid()::varchar, 1, 1, '{}'::json, '{"disposition_codes":[]}'::json, '{}'::json, NOW())
    RETURNING id
)
INSERT INTO workflow_definitions (workflow_id, workflow_json, workflow_configurations, version_number, template_context_variables, status, created_at)
SELECT id, '{"nodes": [{"id": "1", "type": "startCall", "position": {"x": 175, "y": 60}, "data": {"prompt": "# Goal\nYou are an expert sales representative for a modern dine-in ordering software called ''DineFlow''. Your goal is to explain our features, compare us to competitors, collect the caller''s details, and schedule a demo if they are interested.\n\n## Core Features to mention:\n1. QR Code Ordering & Payments\n2. Real-time Kitchen Display System (KDS)\n3. POS Integration\n4. Live Inventory Tracking\n5. Waitlist & Reservation Management\n6. Customer Loyalty Programs\n7. Multi-location Support\n8. AI-driven Analytics Dashboard\n9. Staff Management & Scheduling\n10. Automated SMS Marketing\n\n## Competitor Differentiation:\nWe offer 0% commission on orders, integrate directly with existing POS hardware without needing new tablets, and provide 24/7 localized support unlike other major providers in the market.\n\n## Call Flow:\n1. Greet the user warmly and introduce yourself as a DineFlow expert.\n2. Ask about their restaurant and explain features based on their pain points.\n3. If they are interested, ask for their name, phone number, and preferred demo time.\n4. Tell them you have scheduled a demo and they will receive a WhatsApp/SMS confirmation.", "name": "start call", "allow_interrupt": true, "add_global_prompt": false, "delayed_start": false, "is_start": true, "extraction_enabled": false, "greeting_type": "text", "greeting": "Hello, thanks for calling DineFlow! Are you looking to upgrade your restaurant''s ordering system today?", "delayed_start_duration": 2, "pre_call_fetch_enabled": false}}], "edges": [], "viewport": {"x": 582.0, "y": 121.5, "zoom": 0.75}}'::json, '{}'::json, 1, '{}'::json, 'draft', NOW()
FROM new_workflow;

COMMIT;
