import {
    Activity,
    AlertTriangle,
    ArrowRight,
    Bot,
    Brain,
    Calendar,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronRight,
    Circle,
    ClipboardCheck,
    Clock,
    Cloud,
    Code,
    Copy,
    Cpu,
    CreditCard,
    Database,
    Edit,
    ExternalLink,
    File,
    FileText,
    Folder,
    Globe,
    Headset,
    HelpCircle,
    Info,
    Key,
    Layers,
    Link2,
    Lock,
    Mail,
    MessageSquare,
    Mic,
    Minus,
    OctagonX,
    Pause,
    Phone,
    PhoneCall,
    PhoneOff,
    Play,
    Plus,
    Radio,
    RefreshCw,
    Send,
    Server,
    Settings,
    Share2,
    Shield,
    Sliders,
    Sparkles,
    Square,
    Terminal,
    Trash2Icon,
    Volume2,
    Webhook,
    Workflow,
    Wrench,
    X,
    XCircle,
    Zap,
    type LucideIcon,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
    activity: Activity,
    alerttriangle: AlertTriangle,
    arrowright: ArrowRight,
    bot: Bot,
    brain: Brain,
    calendar: Calendar,
    check: Check,
    checkcircle: CheckCircle,
    chevrondown: ChevronDown,
    chevronright: ChevronRight,
    circle: Circle,
    clipboardcheck: ClipboardCheck,
    clock: Clock,
    cloud: Cloud,
    code: Code,
    copy: Copy,
    cpu: Cpu,
    creditcard: CreditCard,
    database: Database,
    edit: Edit,
    externallink: ExternalLink,
    file: File,
    filetext: FileText,
    folder: Folder,
    globe: Globe,
    headset: Headset,
    helpcircle: HelpCircle,
    info: Info,
    key: Key,
    layers: Layers,
    link2: Link2,
    lock: Lock,
    mail: Mail,
    messagesquare: MessageSquare,
    mic: Mic,
    minus: Minus,
    octagonx: OctagonX,
    pause: Pause,
    phone: Phone,
    phonecall: PhoneCall,
    phoneoff: PhoneOff,
    play: Play,
    plus: Plus,
    radio: Radio,
    refreshcw: RefreshCw,
    send: Send,
    server: Server,
    settings: Settings,
    share2: Share2,
    shield: Shield,
    sliders: Sliders,
    sparkles: Sparkles,
    square: Square,
    terminal: Terminal,
    trash2icon: Trash2Icon,
    trash2: Trash2Icon,
    volume2: Volume2,
    webhook: Webhook,
    workflow: Workflow,
    wrench: Wrench,
    x: X,
    xcircle: XCircle,
    zap: Zap,
};

export function resolveIcon(name?: string): LucideIcon {
    if (!name) return Circle;
    const normalized = name.trim().toLowerCase().replace(/[-_]/g, '');
    return ICON_MAP[normalized] ?? Circle;
}
